[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://connectlive-backend.onrender.com"
  VITE_SOCKET_SERVER_URL = "https://connectlive-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 